name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to destroy'
        required: true
        type: choice
        options:
          - dev
          - staging
      confirm_destroy:
        description: 'Type "destroy" to confirm'
        required: true
        type: string

env:
  TF_VERSION: '1.5.7'
  AWS_REGION: 'us-east-1'

jobs:
  terraform-destroy:
    name: 'Terraform Destroy'
    runs-on: ubuntu-latest
    environment: 
      name: ${{ github.event.inputs.environment }}-destroy
    
    permissions:
      contents: read
      id-token: write
    
    steps:
      - name: Verify Destroy Confirmation
        run: |
          if [ "${{ github.event.inputs.confirm_destroy }}" != "destroy" ]; then
            echo "ERROR: Destroy confirmation does not match. You must type 'destroy' exactly."
            exit 1
          fi

      - name: Checkout code
        uses: actions/checkout@v4

    #   - name: Configure AWS Credentials
    #     uses: aws-actions/configure-aws-credentials@v4
    #     with:
    #       aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #       aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #       aws-region: ${{ env.AWS_REGION }}
    
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::274601145879:role/GithubOIDCRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform init

      - name: Terraform Destroy Plan
        id: destroy-plan
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform plan -destroy -no-color

      - name: Wait for Manual Approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: devops-team
          minimum-approvals: 1
          issue-title: "Approve Terraform Destroy for ${{ github.event.inputs.environment }}"
          issue-body: "Please approve the destruction of ${{ github.event.inputs.environment }} environment"

      - name: Terraform Destroy
        working-directory: ./environments/${{ github.event.inputs.environment }}
        run: terraform destroy -auto-approve

    #   - name: Notify Slack
    #     if: always()
    #     uses: slackapi/slack-github-action@v1.24.0
    #     with:
    #       payload: |
    #         {
    #           "text": "${{ job.status == 'success' && '✅' || '❌' }} Terraform Destroy ${{ job.status }}",
    #           "blocks": [
    #             {
    #               "type": "section",
    #               "text": {
    #                 "type": "mrkdwn",
    #                 "text": "*Terraform Destroy ${{ job.status }}* ${{ job.status == 'success' && '✅' || '❌' }}\n*Environment:* ${{ github.event.inputs.environment }}\n*By:* ${{ github.actor }}"
    #               }
    #             }
    #           ]
    #         }
    #     env:
    #       SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}